name: Bouw Mac App

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5  # Update naar v5 voor de zekerheid
      with:
        python-version: '3.11' 

    - name: Installeer benodigdheden
      run: |
        pip install -r requirements.txt

    - name: Bouw de App met PyInstaller
      run: |
        # --onefile: 1 bestand
        # --windowed: geen zwart schermpje
        # --name: de naam van je app
        pyinstaller --onefile --windowed --name "ExcelMerger" merge_excel.py

    - name: Upload het resultaat
      uses: actions/upload-artifact@v4  # HIER ZAT HET PROBLEEM (Nu v4)
      with:
        name: ExcelMerger
        path: dist
